#!/bin/bash -l

@Library('jenkinslib') _  
//调用方法库文件
def tools = new org.devops.tools()
pipeline {
    
    agent {
      label 'macos4'
    }


    parameters {
        
        // 基本参数/传参

        string(
            name: "Package",
            defaultValue: 'Debug',
            description: '包类型'
        )

        string(
            name: 'Branch', 
            defaultValue: 'main', 
            description: '默认分支或者Tag'
        )

        string(
            name: "RepoUrl",
            defaultValue: '$GITLAB/mimo-app-ios.git',
            description: '代码仓库地址'
        )

        string(
            name: "Version",
            defaultValue: '2.0.0',
            description: 'app版本号'
        )
    }

    environment {


        // 传参转为环境变量
        branch = "$params.Branch"
        url = "$params.RepoUrl"
        packageName = "$params.Package"
        version = "$params.Version"


    }
    
    stages {
        stage('command') {
            steps{
                sh '''
                #rm -rf /Users/apple/Documents/git/jenkins/workspace/MIMO_iOS_Debug/ios_pack/*
                cd ~/ios_test/mimo-app-ios/
                #/bin/bash ./CI.sh $Version $BUILD_NUMBER Debug
                '''
            }
        }
        
    }
    post{
        always {
            wrap([$class: 'BuildUser']) {
                script{
                    result = "${currentBuild.currentResult}"
                    tools.OriginIosAppPackNotifyV2(result)
                }
            }
            
        }
        success {
            archiveArtifacts artifacts: '**/*.ipa'
        
        }
    }
}